### ISSUE TITLE
More Items

### ISSUE THREAD

**Issue by vedisdragon** [MarceloAlves/StarboundItems#15]
Hey uh I have no idea if this is where I should put this but:
item ID for Fleshbringer is fleshstaff, it's not in the app

**Comment by MarceloAlves** [comment]
Hey there. I'll take a look. Was it an item that was added recently or in the nightlies? I haven't updated the database in a few months...

**Comment by vedisdragon** [comment]
I believe it was added in an unstable update recently. Thank you so much for creating this list btw, it's fantastic. 


     On Saturday, April 18, 2015 12:29 AM, Marcelo Alves <notifications@github.com> wrote:
   

 Hey there. I'll take a look. Was it an item that was added recently or in the nightlies? I haven't updated the database in a few months...—

**Comment by Dragonbuilt** [comment]
I need the code for dimond drill and pickaxe

**Comment by MarceloAlves** [comment]
Hey there @Dragonbuilt 

Looks like mining tools were skipped for some reason. I'll work on getting those added in but for now the item names are:

* `diamonddrill`
* `diamondpickaxe`

Thanks for the headsup

**Comment by MarceloAlves** [comment]
@Dragonbuilt you should see the tools in the search results now. Thanks again
