### ISSUE TITLE
Formatted items.json? (plus minify)

### ISSUE THREAD

**Issue by dmitrizagidulin** [MarceloAlves/StarboundItems#26]
Hi Marcelo,

Would you be open to the idea of switching to a pretty-printed (non-minified) items.json? 
(I assume it's minified for size, for deployment). Combined with a shell script to take the formatted json and minify it for deployment?

The main benefit would be - it would be much more human-readable, and people would be able to see the diffs in individual commits, to get an idea of what was added/removed, etc.

**Comment by MarceloAlves** [comment]
Hi there

There actually isn't a good reason for the items json to be minified anymore. Early on I was using the file to filter the results but then switched to storing it in ElasticSearch. Now I just keep the file updated and in there just in case someone else finds it useful.

I just found that the JSON library has a [`pretty_generate`](http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#method-i-pretty_generate) so it's a piece of cake to switch that over. I'll update the current one and all of the future ones will match.

Thanks!

**Comment by dmitrizagidulin** [comment]
Oh, awesome! Thanks!

**Comment by dmitrizagidulin** [comment]
Question - do you have automated scripts that update the ElasticSearch items from nightly diffs / resources, or do you do it by hand?

**Comment by MarceloAlves** [comment]
Sort of by hand. I haven't came up with an automated way of updating it just yet. A lot of the time after the items.json is generated I'll cherry pick some items and make sure their ID's still match. Then I'll take the file and do a bulk index for ES. For this last go around I took the old items and new items in a hash, got the difference and created a list of all new items.

Someday when I trust that the items still have the same ID after every generate I'll have it automated.
