### ISSUE TITLE
Add dev install/setup instructions to readme

### ISSUE THREAD

**Issue by dmitrizagidulin** [MarceloAlves/StarboundItems#27]
Can you add a rough outline on how to set up and run this app locally? Even a high-level overview would help (like "install redis, install elastic search", "write a shell script to iterate through the json and insert documents into ES", etc).

**Comment by MarceloAlves** [comment]
Great idea. I can work something up.

**Comment by MarceloAlves** [comment]
@dmitrizagidulin I've added a Getting Started guide. Let me know if there's some instructions that could be improved!

Thanks

**Comment by dmitrizagidulin** [comment]
Perfect, thank you! I'll try this out! :)
