### ISSUE TITLE
Removed Items

### ISSUE THREAD

**Issue by TheDarkAndroid** [MarceloAlves/StarboundItems#30]
You should remove items that are not in the game anymore

**Comment by MarceloAlves** [comment]
I normally do but was short on time when updating it over the weekend. Haven't had the chance to figure out the difference yet

**Comment by TheDarkAndroid** [comment]
ok

**Comment by Maikuolan** [comment]
Not really related to this issue, but just wanted to mention: Awesome work, BTW. :+1: 

Very useful tool that you've provided here.

**Comment by MarceloAlves** [comment]
@Maikuolan hey thanks! glad it's useful!
