### ISSUE TITLE
The website is infected with a virus?

### ISSUE THREAD

**Issue by Shetoks** [MarceloAlves/StarboundItems#33]
https://www.virustotal.com/ru/url/aa4205ef929082b9b84c39857aaa31eb99ab0d64b16d713922b009521f3ce7d9/analysis/

**Comment by MarceloAlves** [comment]
@Shetoks hmm...that's strange. Maybe a false positive? Don't see why it would claim that

**Comment by Shetoks** [comment]
I don't know. There's a file also claimed as a virus "a469ab4ca4e55bf547566e9ebfa1b809c933207e9d558156bc0c4252b17533fe"
https://www.virustotal.com/en/domain/starbounditems.herokuapp.com/information/
But I've checked the site with 
http://quttera.com/
https://rescan.pro
http://sitecheck.sucuri.net
And they find nothing...

**Comment by MarceloAlves** [comment]
The filename shows as just being `)` so who knows what that could be. The only thing I can think of is if maybe a malicious ad was being served

**Comment by Shetoks** [comment]
So now the site is safe?

**Comment by MarceloAlves** [comment]
Yes, I believe so. I'll keep an eye on it and see if anything turns up. Thanks 👍
