### ISSUE TITLE
Partial word matches not working

### ISSUE THREAD

**Issue by zekrom-vale** [MarceloAlves/StarboundItems#35]
Partial word matches are not matching with anything.  For example 'teleport' gives nothing while 'teleporter' gives a lot of results.  With my spelling issues it is difficult to find some items like cobble or diamond.

**Comment by MarceloAlves** [comment]
Hey @zekrom-vale

I tweaked the query a bit. `Teleport` now shows items container teleporter. But probably still needs some tweaking since `titanium` doesn't show anything when it should.

Give it a shot https://starbounditems.herokuapp.com/?search=teleport
