### ISSUE TITLE
Does not work at all (Firefox)

### ISSUE THREAD

**Issue by UberComplainer** [MarceloAlves/StarboundItems#51]
As the title says... Bloody javascript.

**Comment by UberComplainer** [comment]
Win10, if you're wondering.

**Comment by MarceloAlves** [comment]
Mind trying again? The SSL cert wasn't added so hopefully it works now

**Comment by UberComplainer** [comment]
Umm, sorry for misleading you... The page loads, just the search doesn't work. It just doesn't do anything. Enter doesn't do anything after I type something in. Waiting doesn't help.

**Comment by UberComplainer** [comment]
It used to work just fine a couple of days ago... I mean pressing enter after typing.

**Comment by UberComplainer** [comment]
Does Firefox have a built-in ad-blocker? The site does mention it's supported by ads, but I don't see any.

**Comment by MarceloAlves** [comment]
>It used to work just fine a couple of days ago... I mean pressing enter after typing.

I think it might work now. I hope.

>Does Firefox have a built-in ad-blocker? 

It might. Not too sure.

**Comment by UberComplainer** [comment]
Works perfectly now, even without enter. Thank you!
