### ISSUE TITLE
Quick CSS issue

### ISSUE THREAD

**Issue by ManOrMonster** [MarceloAlves/StarboundItems#7]
The search button is 51 px, but the input is 52 px (I'm using Chrome). However, there doesn't seem to be a need for the search button anyway since the search autocompletes. Does the button even do anything?

**Comment by MarceloAlves** [comment]
@ManOrMonster You're correct. It is pretty much useless! I think I had some plans to hook it up as something to fall back on but never did. I'll probably just remove it. Thanks!

**Comment by ManOrMonster** [comment]
No problem, was dealing with the same issue on a site I'm working on just a few days ago.
